# Generated by Django 4.1.3 on 2022-11-24 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_direction_tutor_remove_discipline_direction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discipline',
            old_name='direction',
            new_name='directions',
        ),
    ]
